# Generated by Django 4.2.7 on 2023-11-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.IntegerField(choices=[(0, '---'), (1, 'Entertainment'), (2, 'Sport')], default=0),
        ),
    ]
